name: degreed
description: "Degreed Flutter Assignment"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  http: ^1.1.0
  cupertino_icons: ^1.0.6
  dartz:
  connectivity_plus: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  bloc_test: ^9.1.7
  
flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
  fonts:
    - family: Agdasima
      fonts:
        - asset: assets/fonts/Agdasima-Regular.ttf

